config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  # resources :reviews
  #root 'reviews#index'
  resources :reviews do
    member do
      get 'map_location'
    end
  end

  devise_for :users

  get 'search/search_by'

  get 'search/cuisine'

  get 'search/rating'

  get 'search/price'

  get 'search/location'

  # Set landing page
  root 'landing_page#index'

  get 'landing_page/login'

  get 'landing_page/signup'

  get 'users/sign_in'

  get 'users/sign_up'

  get 'search/new_search'

  get 'serch/search_all'

  resources :profiles
  # resources :reviews
  #root 'reviews#index'
  resources :reviews do
    member do
      get 'map_location'
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, :birthday, presence: true
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }, default_url: "/images/:style/user_font_awesome.png", default_style: :small

  validates_attachment :image,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    if user_signed_in?
    @user = current_user
    end
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    # @user = User.find(current_user.id)
  end


# INSTEAD OF CRETING A NEW PROFILE USERS WILL UPDATE THE ON CREATED AT SIGN UP
  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit

  end



# PROFILE IS ALREADY BEING CREATED WHEN USERS SIGN UP
# or is it???
  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to  @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :birthday, :about_me, :user_id, :image)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="section-heading">
  <%= form_for(@profile, html: { multipart: true }) do |f| %>

  <% if @profile.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

    <ul>
      <% @profile.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>


  <div class="field">
    <h3><%= f.file_field :image, :class => "white" %></h3>
  </div>

  <div class="field">
    <%= f.label :name, :class => "white" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :birthday, :class => "white" %><br>
    <%= f.date_select :birthday, :start_year => Date.today.year - 100, :end_year => Date.today.year %>
  </div>
  <div class="field">
    <%= f.label :about_me, :class => "white" %><br>
    <%= f.text_area :about_me %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
  <br>
<div class="panel panel-success">

<h1>Editing Profile</h1>
</div>
<br>
<br>

<div class="section-heading">
<h6><%= render 'form' %></h6>
</div>
<br>

<!-- <div class="section-heading"> -->
<!-- <h2><%= link_to 'Back', profiles_path %></h2> -->
<!-- </div> -->

app/views/profiles/index.html.erb
<div class="section-heading">
<p id="notice"><%= notice %></p>
</div>

<div class="section-heading">
<table class="table" style="width:100%">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Birthday</th>
      <th>About me</th>
    </tr>
  </thead>
  </div>
  <tbody>
    <% @profiles.each do |profile| %>
    <tr>

      <% if !profile.image %>
        <%= image_tag profile.image.default_url %>
      <% else %>
        <td><%= image_tag profile.image.url %></td>
      <% end %>
      <td><%= profile.name %></td>
      <td><%= profile.birthday %></td>
      <td><%= profile.about_me %></td>
    </tr>
    <% end %>
  </tbody>
</table>
  <br>

  <div class="section-heading">

    <% if user_signed_in?%>
    <%= link_to 'Edit Profile', edit_profile_path(@user.profile), :class => 'myButton' %>
    <% end %>
    <br/>
  </div>

app/views/profiles/new.html.erb
<div class="section-heading">
<h1>New Profile</h1>
<%= render 'form' %>

<!-- <%#= link_to 'Back', profiles_path %> -->
</div>

app/views/profiles/show.html.erb
<br>
<br>
<div class="section-heading">
  <p id="notice"><%= notice %></p>
</div>
<br>

<div class="section-heading">
    <%= link_to image_tag(@profile.image.url(:large)), @profile.image.url %>
</div>
<br>

<div class="section-heading">
  <p>
    <strong>Name:</strong>
    <%= @profile.name %>
  </p>
</div>
<br/>

<div class="section-heading">
  <p>
    <strong>Birthday:</strong>
    <%= @profile.birthday %>
  </p>
</div>
<br>

<div class="section-heading">
  <p>
    <strong>About me:</strong>
    <%= @profile.about_me %>
  </p>
</div>

<br>
<div class="section-heading">
<%= link_to 'Edit', edit_profile_path(@profile), :class => 'myButton' %>
<!-- <h6><%= link_to 'Back', profiles_path %></h6> -->
</div>
<hr>


<div class="section-heading">
<h1>My Reviews</h1>
</div>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Restaurant name</th>
      <th>Cuisine</th>
      <th>Dish</th>
      <th>Price</th>
      <th>Rating</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Postalcode</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <!--current user has many reviews  -->
    <% current_user.reviews.each do |review| %>
    <tr>
      <td><%= image_tag review.image.url(:small) %></td>
      <!--this link_to will link you to specific restaurant just click the restaurant_name list with review_path(review) -->
      <td><%= link_to review.restaurant_name, review_path(review) %></td>

      <td><%= review.cuisine %></td>
      <td><%= review.dish %></td>
      <td>$<%= review.price %></td>
      <td><% review.rating.times { %> &#x272D; <% } %></td>
      <td><%= review.street %></td>
      <td><%= review.city %></td>
      <td><%= review.state %></td>
      <td><%= review.postalcode %></td>
      <td><%= review.description %></td>
      <td><%= review.user.email %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if !current_user.nil? %>
<%= link_to 'Create Review', new_review_path, :id => "new_review", :class => 'myButton' %>
<% end %>