config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  # resources :reviews
  #root 'reviews#index'
  resources :reviews do
    member do
      get 'map_location'
    end
  end

  devise_for :users

  get 'search/search_by'

  get 'search/cuisine'

  get 'search/rating'

  get 'search/price'

  get 'search/location'

  # Set landing page
  root 'landing_page#index'

  get 'landing_page/login'

  get 'landing_page/signup'

  get 'users/sign_in'

  get 'users/sign_up'

  get 'search/new_search'

  get 'serch/search_all'

  resources :profiles
  # resources :reviews
  #root 'reviews#index'
  resources :reviews do
    member do
      get 'map_location'
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
    # assign review to current_user
    if user_signed_in?
    @user = User.find(current_user.id)
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    
  end

  # GET /reviews/new
  def new
    @review = Review.new
    # @review = Review.find(params[:id])
  end

  # GET /reviews/1/edit
  def edit
  end
  # method 'maplocation' will render map on page
  def map_location
    @review = Review.find(params[:id])
    @hash = Gmaps4rails.build_markers(@review) do |review, marker|
      marker.lat(review.latitude)
      marker.lng(review.longitude)
      marker.infowindow("<em>" + review.street + "</em>")
    end
    render json: @hash.to_json
  end


  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def review_params
    params.require(:review).permit(:latitude, :longitude, :restaurant_name, :cuisine, :dish, :price, :rating, :street, :city, :state, :postalcode, :description, :user_id, :image)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do  |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

  <div class="field">
    <%= f.hidden_field :latitude %>
  </div>

  <div class="field">
    <%= f.hidden_field :longitude %>
  </div>

<div class="container", id="font">
  <div class="row">
    <div class="col-sm-6">

      <div class="field">
        <%= f.label :restaurant_name, :class => "white" %><br>
        <%= f.text_field :restaurant_name %>
      </div>

  <div class="field">
    <%= f.label :cuisine, :class => "white" %><br>
    <%= f.text_field :cuisine %>
  </div>

  <div class="field">
    <%= f.label :dish, :class => "white" %><br>
    <%= f.text_field :dish %>
  </div>

  <div class="field">
    <%= f.label :street, :class => "white" %><br>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city, :class => "white" %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state, :class => "white" %><br>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :postalcode, :class => "white" %><br>
    <%= f.text_field :postalcode %>
  </div>

</div> <!-- class column -->

  <div class="field">
    <%= f.label :image, :class => "white" %><br>
    <%= f.file_field :image, :class => "white" %>
  </div>

  <div class="field">
    <%= f.label :price, :class => "white" %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :rating, :class => "white" %><br>
    <select class="selectpicker" name="review[rating]">
      <option value="">Rating</option>
      <option value="1">&#x272D;</option>
      <option value="2">&#x272D;&#x272D;</option>
      <option value="3">&#x272D;&#x272D;&#x272D;</option>
      <option value="4">&#x272D;&#x272D;&#x272D;&#x272D;</option>
      <option value="5">&#x272D;&#x272D;&#x272D;&#x272D;&#x272D;</option>
    </select>
  </div>

  <div class="field">
    <%= f.label :description, :class => "white" %><br>
    <%= f.text_area :description, :cols => "40", :rows => "10" %>
  </div>

</div> <!-- class column -->

  <div class="field">
    <!-- User id field hidden and automatically fill-in by current user id -->
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <!-- id not allowed in embedded ruby. when testing, do: '#create_review input' -->
<div class="field">
  <!-- User id field hidden and automatically fill-in by current user id -->
  <%= f.hidden_field :user_id, :value => current_user.id %>
</div>

<div class="section-heading">
</br>
<!-- id not allowed in embedded ruby. when testing, do: '#create_review input' -->
<div class="actions" id="create_review">
    <%= f.submit 'Create Review', :class => "myButton" %>
</div>
<% end %>
</div>
</div>

app/views/reviews/edit.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  Editing Review
  </div>
</div>


<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  Latest Reviews
  </div>
</div>


<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Restaurant name</th>
      <th>Cuisine</th>
      <th>Dish</th>
      <th>Price</th>
      <th>Rating</th>
      <th>Address</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
    <tr>
      <td><%= image_tag review.image.url(:small) %></td>
      <!--this link_to will link you to specific restaurant just click the restaurant_name list with review_path(review) -->
      <td><%= link_to review.restaurant_name, review_path(review), class: "restaurant_link" %></td>

      <td><%= review.cuisine %></td>
      <td><%= review.dish %></td>
      <td>$<%= review.price %></td>
      <td><% review.rating.times { %> &#x272D; <% } %></td>
      <td><%= review.full_address %></td>
      <td><%= review.description %></td>
      <td><%= review.user.email %></td>
      <% if user_signed_in? && current_user.id == review.user_id %>
        <td><%= link_to 'Edit', edit_review_path(review), class: "edit_link" %></td>
        <td><%= link_to 'Destroy', review, class: "destroy_link", method: :delete, data: {confirm: 'Are you sure'} %></td>
        <% else %>
          <td></td>
          <td></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="section-heading">
<% if !current_user.nil? %>
<%= link_to 'Create Review', new_review_path, :id => "new_review", :class => 'myButton' %>
<% end %>
</div>

app/views/reviews/new.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  New Review
  </div>
</div>


<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>Latitude:</strong>
  <%= @review.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @review.longitude %>
</p> -->
<div class="container" id="reviews_show">
  <br>
  <p>
    <strong>Restaurant name:</strong>
    <%=  @review.restaurant_name %>
  </p>
  <br>
  <p>
    <strong>Cuisine:</strong>
    <%= @review.cuisine %>
  </p>
  <br>
  <p>
    <strong>Dish:</strong>
    <%= @review.dish %>
  </p>
  <br>
  <p>
    <strong>Price:</strong>
    <%= @review.price %>
  </p>
  <br>
  <p>
    <strong>Rating:</strong>
    <% @review.rating.times { %> &#x272D; <% } %>
  </p>
  <br>
  <p>
    <strong>Street:</strong>
    <%= @review.street %>
  </p>
  <br>
  <p>
    <strong>City:</strong>
    <%= @review.city %>
  </p>
  <br>
  <p>
    <strong>State:</strong>
    <%= @review.state %>
  </p>
  <br>
  <p>
    <strong>Postalcode:</strong>
    <%= @review.postalcode %>
  </p>
  <br>
  <p>
    <strong>Description:</strong>
    <%= @review.description %>
  </p>
  <br>
  <p>
    <strong>User:</strong>
    <%= @review.user.email %>
  </p>
  <br>
  <p><%= link_to 'Back', reviews_path, class: "back_link" %></p>
  <br>
  <% if user_signed_in? && current_user.id == @review.user_id %>
    <%= link_to 'Edit', edit_review_path(@review), class: "edit_link" %> |
  <% end %>
  <br>
  <%= image_tag @review.image.url, id: "review_image" %>

  <div id="restaurant_map" class="container" data-review-id="<%=@review.id%>"></div>
</div>
<!-- div contains google map -->